In [26]:
import pandas as pd
import matplotlib as plt
import numpy as np

In [27]:
#import csv file and create dataframe
csv_path  = "Resources/OSF_socialmedia_data.csv"
social_media_df = pd.read_csv(csv_path)
social_media_df.head()

,Unnamed: 0,Participant,Date,Day,Time,Session.Name,Notification.No,LifePak.Download.No,Responded,Completed.Session,...,Loneliness,Concentrat,LossOfInt,Inferior,Hopeless,Stress,PSMU,AutoPSMU,News,Active
0,1,115091,05/02/2017,Tuesday,10:00:06,Daily questions,1,1,1,1,...,61.0,64.0,68.0,50.0,56.0,73.0,66.0,66,39.0,38.0
1,2,115091,05/02/2017,Tuesday,12:02:48,Daily questions,2,1,1,1,...,57.0,70.0,58.0,37.0,56.0,67.0,0.0,#skipped#,27.0,23.0
2,3,115091,05/02/2017,Tuesday,14:03:02,Daily questions,3,1,1,1,...,44.0,70.0,67.0,26.0,38.0,39.0,63.0,56,34.0,36.0
3,4,115091,05/02/2017,Tuesday,16:34:28,Daily questions,4,1,1,1,...,56.0,79.0,89.0,30.0,20.0,60.0,67.0,68,29.0,23.0
4,5,115091,05/02/2017,Tuesday,18:00:00,Daily questions,5,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#count to determine missing values
social_media_df.count()

Unnamed: 0                         12245
Participant                        12245
Date                               12245
Day                                12245
Time                               12245
Session.Name                       12245
Notification.No                    12245
LifePak.Download.No                12245
Responded                          12245
Completed.Session                  12245
Session.Instance                    8695
Session.Instance.Response.Lapse     8695
Reminders.Delivered                12245
Instr_DQs                              0
Fatigue                             8653
DeprMood                            8648
Loneliness                          8646
Concentrat                          8645
LossOfInt                           8646
Inferior                            8646
Hopeless                            8650
Stress                              8649
PSMU                                8646
AutoPSMU                            8651
News                                8647
Active                              8645
dtype: int64

In [43]:
#cleaned up data 
social_media_df.dropna(how = "all")


cleaned_social_media = social_media_df.drop(['LifePak.Download.No','Session.Name', 'Session.Instance.Response.Lapse', 'Instr_DQs', 'Unnamed: 0'], axis = 1)
cleaned_social_media = cleaned_social_media.fillna(0)
cleaned_social_media.head(10)

#remove_nan = cleaned_social_media[cleaned_social_media['Session.Instance'] == 'NaN' ].index
#cleaned_social_media.drop(remove_nan , inplace=True)
cleaned_social_media.to_csv('Resources/cleaned_data.csv')